<program> ::= <class> | <stmt_list> | <function_list> 

<class> ::= public <class_name> {<stmt_list> | <function_list>} | <class_name> {<stmt_list> | <function_list>} 

<function_list> ::= <function> | <function><function_list>

<function> ::= <return_type> <name>(<arg>){<stmt_list>}

<stmt_list> ::= <stmt>; | <stmt>; <stmt_list> | <condition_list> <stmt_list> | <iteration> <stmt_list> 

<condition_list> ::= <condition_start> | <condition_start> <condition_end_list> | if(<condition>) ? <stmt> : <stmt>

<condition_start> ::= if(<condition>){<stmt_list>}

<condition_end_list> ::= <condition_end> | <condition_end> <condition_end_list>

<condition_end> ::= else(<condition>){<stmt_list>} | else{<stmt_list>}

<iteration> ::= while(<condition>){<stmt_list>}

<condition> ::= <bool> | <var><cn_op><var> 

<data> = <bool> | <string> | <integer> | <float> 

<stmt> ::= <var> = <expr> | <var><ar_op> | <name>(<arg>) | return <var>;

<expr> ::= <var> | <var> <ar_op> <var> | <name>(<arg>)

<var> ::= <name> | <data>



<bool> ::= true | false

<string> ::= ".*"

<integer> ::= [0-9]*

<float> ::= [0-9]*\.[0-9]*

<name> ::= [a-zA-Z](?:[a-zA-Z0-9_])*

<cn_op> ::= == | != | > | < | >= | <=

<ar_op> ::= + | - | * | / | += | -= | *= | /= | % | ++ | -- | **